### ISSUE TITLE
新发布版破坏了 Laravel 6 的兼容性

### ISSUE THREAD

**Issue by greenhat616** [HyanCat/aliyun-direct-mail#4]
* 没有重新部署配置（按照 semver 的补丁版本应该不用吧）
* 直接更新依赖到新版本，使用 .env 配置且未作任何修改。
* 使用的其他配置或扩展
  * `php artisan optimize`
  * `php artisan view:cache`
  * `laravel-s`
* Laravel 版本： 6.18.2
* 报错日记（移除敏感部分的信息）：
```
[2020-03-20 15:37:37] local.ERROR: Driver [directmail] not supported. {"userId":,"exception":"[object] (InvalidArgumentException(code: 0): Driver [directmail] not supported. at /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php:119)
[stacktrace]
#0 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\\Support\\Manager->createDriver()
#1 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(94): Illuminate\\Support\\Manager->driver()
#2 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Mail\\MailServiceProvider->Illuminate\\Mail\\{closure}()
#3 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#4 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#5 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#6 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#7 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(1245): Illuminate\\Foundation\\Application->make()
#8 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Mail/MailServiceProvider.php(40): Illuminate\\Container\\Container->offsetGet()
#9 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Mail\\MailServiceProvider->Illuminate\\Mail\\{closure}()
#10 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#11 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#12 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#13 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#14 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make()
#15 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass()
#16 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies()
#17 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()
#18 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()
#19 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()
#20 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()
#21 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(95): Illuminate\\Foundation\\Application->make()
#22 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(115): Illuminate\\Notifications\\ChannelManager->createMailDriver()
#23 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(109): Illuminate\\Support\\Manager->createDriver()
#24 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\\Notifications\\ChannelManager->createDriver()
#25 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(146): Illuminate\\Support\\Manager->driver()
#26 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(105): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#27 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#28 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(107): Illuminate\\Notifications\\NotificationSender->withLocale()
#29 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(79): Illuminate\\Notifications\\NotificationSender->sendNow()
#30 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\\Notifications\\NotificationSender->send()
#31 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\\Notifications\\ChannelManager->send()
#32 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Auth/MustVerifyEmail.php(38): App\\User->notify()
#33 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Auth/VerifiesEmails.php(67): Illuminate\\Foundation\\Auth\\User->sendEmailVerificationNotification()
#34 [internal function]: App\\Http\\Controllers\\Auth\\VerificationController->resend()
#35 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#36 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#37 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#38 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#39 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#40 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#41 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#43 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#45 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#47 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#49 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#51 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#53 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#55 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#56 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#57 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#58 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#59 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#60 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#61 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#62 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#63 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#64 /home/runtime/sites/hitokoto/www/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#66 /home/runtime/sites/hitokoto/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#67 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fruitcake\\Cors\\HandleCors->handle()
#68 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#69 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#70 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#72 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#74 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#76 /home/runtime/sites/hitokoto/www/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#78 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#80 /home/runtime/sites/hitokoto/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#81 /home/runtime/sites/hitokoto/www/vendor/hhxsv5/laravel-s/src/Illuminate/Laravel.php(155): Illuminate\\Foundation\\Http\\Kernel->handle()
#82 /home/runtime/sites/hitokoto/www/vendor/hhxsv5/laravel-s/src/LaravelS.php(211): Hhxsv5\\LaravelS\\Illuminate\\Laravel->handleDynamic()
#83 /home/runtime/sites/hitokoto/www/vendor/hhxsv5/laravel-s/src/LaravelS.php(157): Hhxsv5\\LaravelS\\LaravelS->handleDynamicResource()
#84 [internal function]: Hhxsv5\\LaravelS\\LaravelS->onRequest()
#85 /home/runtime/sites/hitokoto/www/vendor/hhxsv5/laravel-s/src/Swoole/Server.php(346): Swoole\\Server->start()
#86 /home/runtime/sites/hitokoto/www/vendor/hhxsv5/laravel-s/src/Console/Portal.php(136): Hhxsv5\\LaravelS\\Swoole\\Server->run()
#87 /home/runtime/sites/hitokoto/www/vendor/hhxsv5/laravel-s/src/Console/Portal.php(56): Hhxsv5\\LaravelS\\Console\\Portal->start()
#88 /home/runtime/sites/hitokoto/www/vendor/symfony/console/Command/Command.php(255): Hhxsv5\\LaravelS\\Console\\Portal->execute()
#89 /home/runtime/sites/hitokoto/www/bin/laravels(160): Symfony\\Component\\Console\\Command\\Command->run()
#90 {main}
"} 

```

**Comment by greenhat616** [comment]
另外建议使用确切的 Semver 版本替代 `dev-master` 的用法，这样版控很方便。
目前使用了 `composer require hyancat/aliyun-direct-mail:dev-master#1887f7
178e5d6642a106509b097bf1350aa62dad` 回滚，此版本可以正确使用。

**Comment by HyanCat** [comment]
临时打了几个 tag。由于精力有限，这个库可能不再维护了，最初也只是自用。建议后续可以迁移到其他的库。

**Comment by HyanCat** [comment]
6.x 使用 0.2.0 版本，临时就固定版本号吧。
